site_name: GDG Córdoba - Android básico

pages:
  - Inicio: index.md
  - Crear proyecto: create_project.md
  - Organizar la vista: vista.md
  - Usando una API externa: api.md
  - Crear un listado: listado.md
  - Nuestra primera vista: vista.md
  - Inflando la vista: inflando_vista.md
  - Haciendo una petición al servidor: pidiendo_datos.md

theme: 'material'
