site_name: GDG Córdoba - Android básico

pages:
  - Inicio: index.md
  - Crear proyecto: create_project.md
  - Organizar la vista: vista.md
  - Usando constantes como recursos: constantes.md
  - Usando una API externa: api.md
  - Crear un listado: listado.md
  - Nuestra primera vista: vista.md
  - Inflando la vista: inflando_vista.md
  - Haciendo una petición al servidor: pidiendo_datos.md
  - Abrir una nueva actividad: nueva_actividad.md

theme: 'material'
site_favicon: 'img/favicon.ico'

extra:
  logo: 'img/logo.png'

repo_name: 'GDGCordoba/android_uco'
repo_url: 'https://github.com/GDGCordoba/android_uco.github.io.git'
